elaticjob:
  zookeeper:
    server-lists: 127.0.0.1:2181
    namespace: boot-job


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: derbysoft
    type: com.zaxxer.hikari.HikariDataSource
  #  自动创建更新验证数据库结构
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect


server:
  port: 8082
